# Generated by Django 5.0.14 on 2026-05-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirportLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iata_code", models.CharField(max_length=10, unique=True)),
                ("airport_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Scope 1", "Scope 1"),
                            ("Scope 2", "Scope 2"),
                            ("Scope 3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=255, unique=True)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=6, help_text="kg CO2e per unit", max_digits=12
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Base unit, e.g., L, kWh, p-km, room-night",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP (Fuel & Procurement)"),
                            ("UTILITY", "Utility Portal CSV (Electricity)"),
                            ("TRAVEL", "Corporate Travel Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial (Some errors)"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUCCESS",
                        max_length=15,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("row_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Scope 1", "Scope 1"),
                            ("Scope 2", "Scope 2"),
                            ("Scope 3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit", models.CharField(max_length=50)),
                ("co2e_kg", models.DecimalField(decimal_places=4, max_digits=18)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("plant_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "origin_airport",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "destination_airport",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("cabin_class", models.CharField(blank=True, max_length=50, null=True)),
                ("hotel_nights", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "validation_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation strings or code issues",
                    ),
                ),
                (
                    "original_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A clean dictionary of original headers/values for visual inspection",
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.ingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_by", models.CharField(default="System", max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(help_text="Rationale for the adjustment")),
                (
                    "normalized_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="api.normalizedactivity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawSourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                (
                    "raw_data",
                    models.JSONField(help_text="Original unmodified CSV row payload"),
                ),
                (
                    "processed_status",
                    models.CharField(default="PENDING", max_length=20),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="api.ingestionjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="raw_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized_activities",
                to="api.rawsourcerecord",
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestion_jobs",
                to="api.tenant",
            ),
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "grid_emission_factor",
                    models.DecimalField(
                        decimal_places=4, help_text="kg CO2e per kWh", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="api.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "plant_code")},
            },
        ),
    ]
